Aristo3: NEW: Material icon image
cappuccino/cappuccino pull request #2909
Opened 2020-08-25 14:27 UTC by didierkorthoudt

Introduction of material icon image (_CPMaterialIconImage)

2020-08-27 10:07 UTC, didierkorthoudt commented
+FIFO

2020-08-28 15:58 UTC, didierkorthoudt commented
I need to complete this one with specific Material Icons font.

2020-09-05 15:25 UTC, didierkorthoudt commented
+FIFO

2020-10-02 09:05 UTC, mrcarlberg requested changes

2020-10-02 09:05 UTC, mrcarlberg commented on AppKit/CPImage.j
> +        if (arguments[1] !== nil && arguments[1] !== undefined)
Please use `arguments[1] != nil` instead of `arguments[1] !== nil && arguments[1] !== undefined` as it is equivalent and much more clean looking

2020-10-02 09:05 UTC, mrcarlberg commented on AppKit/CPImage.j
> +    if (aFilename === undefined || aFilename === nil)
Please use `aFilename == nil` instead of `aFilename === undefined || aFilename === nil` as it is equivalent and much more clean looking

2020-10-02 09:20 UTC, mrcarlberg commented on AppKit/CPImage.j
> +        if (arguments[1] !== nil && arguments[1] !== undefined)
And I guess we could remove this if statement altogether as `typeof(arguments[1]) === "number")`  will imply that arguments[1]` can't be `nil` or `undefined`.

2020-10-02 10:10 UTC, mrcarlberg approved these changes

2020-10-02 10:13 UTC, merged

2020-10-02 10:13 UTC, mrcarlberg commented
Merged! Thanks!