Aristo3: CPSearchField
cappuccino/cappuccino pull request #2934
Opened 2020-08-29 20:34 UTC by didierkorthoudt

This PR adds : 
- new theme parameters, including animation
- modern Cocoa behavior
- Aristo3 CSS theme ready

2020-10-09 13:02 UTC, mrcarlberg requested changes

2020-10-10 15:48 UTC, didierkorthoudt commented on AppKit/CPSearchField.j
> +        searches = [searches subarrayWithRange:CPMakeRange(0, max)];
Strange… Don't remember why I did this this way… I think I wanted to avoid a potential side effect but there's a simpler solution.

2020-10-23 07:02 UTC, mrcarlberg approved these changes

2020-10-23 07:05 UTC, merged

2020-10-23 07:05 UTC, mrcarlberg commented
Merged! Thanks!

2020-10-23 09:54 UTC, cacaodev commented
I should have asked before but what is this "layout-function" theme attribute ? what is the use case, is it needed or useful and if it's a new feature we want why would it be specific to CPSearchField and not implemented in all views ?

2020-11-05 15:41 UTC, didierkorthoudt commented
@cacaodev Well, the layout-function of CPSearchField represents the animation that will be called when the field gets or loses the focus. As it depends on how the theme implements the layout of the search field, it must be a theme parameter. This also ensures retro-compatibility without using ```if``` statements in the code.

I don't think this is something that could be useful for all types of views as it is specific to a particular behavior of ```CPSearchField``` (trying to mimic modern Cocoa).

But this "function as a theme parameter" technic is useful. For example, ```CPTableView``` uses it for column reordering animations…

Did I answered your questions ?

2021-04-17 08:42 UTC, stewa commented
@didierkorthoudt It looks like this PR maybe broke resizing. In my test with a cib with `CPSearchField` and `CPViewWidthSizable` everything seems to resize except the bezel.

2021-04-17 11:53 UTC, daboe01 commented
for me, the bezel is not drawn. in cappusance, i can get the bezel back when setting the min-size explicitly. i will have to make a pure code reduction asap to track this down.